# Generated by Django 5.2.4 on 2025-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
